// *******************************************************************
// AHB system generator - Simplified AHB Decoder & Slave Multiplexer
// *******************************************************************
`timescale 1ns/1ps
`include "ahb_package.vh"

module ahb_decoder #(
    parameter NUM_ARB_MSTS = 4,   // number of masters
    parameter NUM_SLVS     = 4,   // number of slaves

// Slave address ranges - flat arrays, index 0..NUM_SLVS-1
    parameter [32*NUM_SLVS-1:0] ADDR_LOW_FLAT  = 0,
    parameter [32*NUM_SLVS-1:0] ADDR_HIGH_FLAT = 0
)(
    input  wire        hresetn,
    input  wire        hclk,

    // Inputs from the Selected Master (From Arbiter output)
    input  wire [3:0]  master_sel,        // Current master index selected for the Address Phase
    input  wire [31:0] sel_haddr,         // Multiplexed address from winning master
    input  wire [1:0]  sel_htrans,        // Multiplexed transfer status type from winning master

// Slave inputs - multiplexed signals driven out by the arbiter/decoder to all slaves 

    output wire [NUM_SLVS-1:0] slv_hsel,          // Individual select line mux for each slave generated by decoder
    output wire                hready,      // Global ready status sent to all slaves  

    // Slave outputs - signals driven back from individual slaves into the arbiter

    input  wire [NUM_SLVS-1:0] slv_hready_in_v,      // Array of ready signals from each individual slave
    input  wire [NUM_SLVS*2-1:0]  slv_hresp_flat,  // Array of response types from each individual slave; [2*(i+1)-1:2*i] = slave i hresp
    input  wire [NUM_SLVS*32-1:0] slv_hrdata_flat, // Array of read data buses from each individual slave; [32*(i+1)-1:32*i] = slave i hrdata

    // Multiplexed Slave outputs sent back to Master pipeline
    output reg         slv_hready_mux,  // Ready signal chosen from the active slave
    output reg  [1:0]  slv_hresp_mux,   // 2-bit Response code chosen from the active slave
    output reg  [31:0] slv_hrdata_mux   // Read data chosen from the active slave
);

// Internal signals

    integer i; // Global loop iterators used across various combinatorial blocks

    //memory map decoding
    reg [NUM_SLVS-1:0] hsel_comb;
    reg [NUM_SLVS-1:0] r_slv_hsel;          // Registered version of slave select lines to track data phase slave
    
    // change by agy: variable to track the last active master/slave for the hready_mux
    reg [NUM_SLVS-1:0] last_active_slave;
    // change by agy: force a 1-cycle wait state at the start of the data phase
    reg                force_wait_state;
    reg                def_slave_hsel_comb; // Combinatorial select signal for the default/unmapped slave space
    reg                def_slave_err_phase;   // Cycle 1 of AHB error handshake: hready=0, hresp=ERROR
    //        AHB requires hresp=ERROR on BOTH cycles of the error handshake..
    reg                def_slave_err_second; // Cycle 2 of AHB error handshake: hready=1, hresp=ERROR
    reg                def_slave_hready;  // Internal tracking register for default slave's standard HREADY output
    reg [31:0]         addr_low_tmp;      // Temporary variable holding the lower address bounds during decoder loop checks
    reg [31:0]         addr_high_tmp;     // Temporary variable holding the upper address bounds during decoder loop checks

    // -----------------------------------------------------------------------
    // Slave Mux Passthrough
    // data phase from chosen slave to master
    // -----------------------------------------------------------------------

    always @(*) begin
        // Baseline fallbacks if no slave is active in the data phase
        // slv_hready_mux = def_slave_hready; // change by agy
        
        // change by agy: use last active master/slave's ready as default
        slv_hready_mux = def_slave_hready;
        for (i = 0; i < NUM_SLVS; i = i + 1) begin
            if (last_active_slave[i]) begin
                slv_hready_mux = slv_hready_in_v[i];
            end
        end

        slv_hrdata_mux = 32'h0;
        
        // FIX: Only let the default slave drive ERROR_RESP if no valid slave is selected
        if (|r_slv_hsel) begin //r_slv_hsel or slv_hsel?
            slv_hresp_mux = `OK_RESP; 
        end else begin
            slv_hresp_mux = (def_slave_err_phase || def_slave_err_second) ? `ERROR_RESP : `OK_RESP;
        end

        // Overwrite defaults with active slave selections
        for (i = 0; i < NUM_SLVS; i = i + 1) begin
            if (r_slv_hsel[i]) begin
                slv_hready_mux = slv_hready_in_v[i];
                slv_hresp_mux  = slv_hresp_flat[2*i+:2];
                slv_hrdata_mux = slv_hrdata_flat[32*i+:32];
            end
        end

        // change by agy: drop hready immediately after address phase ends
        if (force_wait_state) begin
            slv_hready_mux = 1'b0;
        end
    end

    //if any slave is selected, readiness of current slave = slv_hready_mux
    //else, readiness of slave = def_slave_hready
// FIX: Prevents the default slave from deadlocking the bus during a valid data phase
    // assign hready = (|r_slv_hsel) ? slv_hready_mux : 
    //                       (def_slave_err_phase) ? def_slave_hready : 1'b1; // change by agy
    // change by agy: allow hready to follow slv_hready_mux (which tracks last active slave) when idle
    assign hready = (|r_slv_hsel) ? slv_hready_mux : 
                          (def_slave_err_phase) ? def_slave_hready : slv_hready_mux;
    // -----------------------------------------------------------------------
    // AHB Decoder
    // -----------------------------------------------------------------------

    always @(*) begin
            hsel_comb = {NUM_SLVS{1'b0}};
            def_slave_hsel_comb = 1'b1;
    
            if (sel_htrans != `IDLE) begin
                for (i = 0; i < NUM_SLVS; i = i + 1) begin
                    // Directly slice the flat parameter using the loop index
                    addr_low_tmp  = ADDR_LOW_FLAT[32*i +: 32];
                    addr_high_tmp = ADDR_HIGH_FLAT[32*i +: 32];
                    
                    // Compare the full 32-bit space to ensure zero-padding doesn't break alignment
                    if (sel_haddr >= addr_low_tmp && sel_haddr <= addr_high_tmp) begin
                        hsel_comb[i]        = 1'b1;
                        def_slave_hsel_comb = 1'b0;
                    end
                end
            end
        end

    always @(posedge hclk or negedge hresetn) begin
        if (!hresetn) begin
            r_slv_hsel       <= {NUM_SLVS{1'b0}};
            last_active_slave <= {NUM_SLVS{1'b0}}; // change by agy
            force_wait_state  <= 1'b0; // change by agy
        end
        else if (hready) begin
            r_slv_hsel       <= hsel_comb;
            // change by agy: track last active master/slave
            if (|hsel_comb) begin
                last_active_slave <= hsel_comb;
                // change by agy: trigger forced wait state for the next cycle (data phase)
                force_wait_state <= 1'b1;
            end else begin
                force_wait_state <= 1'b0;
            end
        end else begin
            // change by agy: release forced wait state after 1 cycle
            force_wait_state <= 1'b0;
        end
    end

    assign slv_hsel = hsel_comb;
    // -----------------------------------------------------------------------
    // Default Slave
    //
    // Implements the 2-cycle AHB error handshake for unmapped addresses:
    //
    //   Cycle N   (address phase):  address decoded, def_slave_hsel_comb=1
    //             trigger fires at posedge N
    //   Cycle N+1 (error cycle 1):  hready=0, hresp=ERROR   [def_slave_err_phase=1]
    //             posedge N+1 transitions to cycle 2
    //   Cycle N+2 (error cycle 2):  hready=1, hresp=ERROR   [def_slave_err_second=1]
    //             master samples hready=1+ERROR and terminates transfer
    //             posedge N+2 clears all flags
    //   Cycle N+3: idle, normal operation resumes
    // -----------------------------------------------------------------------

// -----------------------------------------------------------------------
    // Default Slave - FIXED ERROR STATE HANDSHAKE
    // -----------------------------------------------------------------------
    always @(posedge hclk or negedge hresetn) begin
        if (!hresetn) begin
            def_slave_hready    <= 1'b1;
            def_slave_err_phase  <= 1'b0;
            def_slave_err_second <= 1'b0; 
        end else begin
            // 1. Process active cycle 2 of an error handshake
            if (def_slave_err_second) begin
                def_slave_err_second <= 1'b0;
                def_slave_hready     <= 1'b1; // Ensure ready returns high after error finishes
            end 
            // 2. Process active cycle 1 of an error handshake
            else if (def_slave_err_phase) begin
                def_slave_hready     <= 1'b1;
                def_slave_err_phase  <= 1'b0;
                def_slave_err_second <= 1'b1;  // Hold ERR_RESP through cycle 2
            end 
            // 3. Only kick off a new error if an unmapped address is actively hitting the bus
            else if (def_slave_hsel_comb && hready && (sel_htrans == `NONSEQ || sel_htrans == `SEQ)) begin
                def_slave_hready    <= 1'b0;
                def_slave_err_phase <= 1'b1;
            end 
            // 4. Safe recovery/idle state behavior
            else begin
                def_slave_hready    <= 1'b1;
                def_slave_err_phase <= 1'b0;
            end
        end
    end
endmodule

