// *******************************************************************
// AHB system generator - AHB Arbiter (converted from VHDL)
// Original Author: Federico Aglietti, federico.aglietti@opencores.org
// *******************************************************************
// AHB arbiter, decoder, master mux, slave mux and default slave in one block.
// Supports fixed/round-robin/random arbitration (alg_number 0-5).
// Up to 15 masters and 15 slaves.

`include "ahb_package.vh"

module ahb_arbiter #(
    parameter NUM_ARB      = 0,   // arbiter index (selects from arb_matrix)
    parameter NUM_ARB_MSTS = 4,   // number of masters
    parameter DEF_ARB_MST  = 0,   // default master index
    parameter NUM_SLVS     = 3,   // number of slaves
    parameter ALG_NUMBER   = 0,   // 0=fixed,1=rr,2=random,3=fair-fixed,4=fair-rr,5=fair-random

    // Slave address ranges – flat arrays, index 0..NUM_SLVS-1
    // Each slave: ADDR_LOW_i, ADDR_HIGH_i (bits [31:10] used for comparison)
    // Pass as parameters or override by external logic if generated by tool
    parameter [32*16-1:0] ADDR_LOW_FLAT  = 0,
    parameter [32*16-1:0] ADDR_HIGH_FLAT = 0
)(
    input  wire        hresetn,
    input  wire        hclk,
    input  wire        remap,

    // Master outputs (what each master drives onto bus) – flattened
    // For master i: hbusreq@[i], hlock@[i], htrans@[2i+1:2i], etc.
    // To keep the interface clean we use individual arrays via generate.
    // Signals for each master (indexed 0..NUM_ARB_MSTS-1)
    input  wire [14:0] mst_hbusreq,   // [i] = master i hbusreq
    input  wire [14:0] mst_hlock,
    input  wire [29:0] mst_htrans,    // [2i+1:2i] = master i htrans
    input  wire [31:0] mst_haddr   [0:14],
    input  wire [14:0] mst_hwrite,
    input  wire [2:0]  mst_hsize   [0:14],
    input  wire [2:0]  mst_hburst  [0:14],
    input  wire [3:0]  mst_hprot   [0:14],
    input  wire [31:0] mst_hwdata  [0:14],

    // Master inputs (what arbiter feeds back to each master)
    output wire [14:0] mst_hgrant,
    output wire        mst_hready_out,   // shared hready to all masters
    output wire [1:0]  mst_hresp_out,    // shared hresp to all masters
    output wire [31:0] mst_hrdata_out,   // shared hrdata to all masters

    // Slave inputs (what arbiter drives to slaves) – per slave
    output wire [NUM_SLVS-1:0] slv_hsel,
    output wire [31:0]         slv_haddr_out,
    output wire                slv_hwrite_out,
    output wire [1:0]          slv_htrans_out,
    output wire [2:0]          slv_hsize_out,
    output wire [2:0]          slv_hburst_out,
    output wire [3:0]          slv_hprot_out,
    output wire [31:0]         slv_hwdata_out,
    output wire [3:0]          slv_hmaster_out,
    output wire                slv_hmastlock_out,
    output wire                slv_hready_in,  // hready fed into slaves

    // Slave outputs (what each slave drives back)
    input  wire [NUM_SLVS-1:0] slv_hready_in_v,
    input  wire [1:0]          slv_hresp_v   [0:14],
    input  wire [31:0]         slv_hrdata_v  [0:14],
    input  wire [15:0]         slv_hsplit_v  [0:14]
);

    // -----------------------------------------------------------------------
    // Internal signals
    // -----------------------------------------------------------------------
    integer i, j;

    reg  [3:0]  grant_master, s_grant_master;
    reg  [3:0]  master_sel, s_master_sel;
    reg  [3:0]  r_master_sel, s_r_master_sel;

    reg  [3:0]  turn, s_turn;
    reg  [9:0]  seed, s_seed;
    reg  [3:0]  random;

    wire [1:0]  htrans_of_sel;  // htrans of current master_sel
    reg  [1:0]  htrans_reg;

    wire        req_ored;
    reg  [14:0] hbusreq_msk;
    reg  [14:0] split_reg;

    // Registered slave sel
    reg  [NUM_SLVS-1:0] r_slv_hsel;
    reg                  r_def_slave_hsel;

    // Selected master bus signals (muxed)
    reg  [31:0] sel_haddr;
    reg  [31:0] sel_hwdata;
    reg         sel_hwrite;
    reg  [2:0]  sel_hsize;
    reg  [2:0]  sel_hburst;
    reg  [3:0]  sel_hprot;
    reg  [1:0]  sel_htrans;

    // Selected slave response (muxed)
    reg         slv_hready_mux;
    reg  [1:0]  slv_hresp_mux;
    reg  [31:0] slv_hrdata_mux;

    wire        s_dec_hready;
    wire        def_slave_hready_w;
    reg         def_slave_hready;
    wire        def_slave_hsel_w;

    // -----------------------------------------------------------------------
    // Bus-request masking (mask busy/split/locked masters)
    // -----------------------------------------------------------------------
    always @(*) begin
        for (i = 0; i < NUM_ARB_MSTS; i = i + 1) begin
            if ((mst_htrans[2*i+1:2*i] == `BUSY) ||
                split_reg[i] ||
                (grant_master != NUM_ARB_MSTS && grant_master != i &&
                 mst_hlock[grant_master]))
                hbusreq_msk[i] = 1'b0;
            else
                hbusreq_msk[i] = mst_hbusreq[i];
        end
        // mask unused slots
        for (i = NUM_ARB_MSTS; i < 15; i = i + 1)
            hbusreq_msk[i] = 1'b0;
    end

    assign req_ored = |hbusreq_msk[NUM_ARB_MSTS-1:0];

    // -----------------------------------------------------------------------
    // Arbitration: fixed priority
    // -----------------------------------------------------------------------
    task fixed_priority;
        output [3:0] t_grant;
        input  [14:0] req;
        integer ii;
        begin
            t_grant = 4'd0;
            for (ii = 0; ii < NUM_ARB_MSTS; ii = ii + 1)
                if (req[ii]) t_grant = ii[3:0];
        end
    endtask

    // Round-robin and random arbitration inline below

    // -----------------------------------------------------------------------
    // s_dec_hready – hready seen by decoder (from selected slave or default)
    // -----------------------------------------------------------------------
    always @(*) begin
        slv_hready_mux = def_slave_hready;
        slv_hresp_mux  = `ERROR_RESP;
        slv_hrdata_mux = 32'hx;
        for (i = 0; i < NUM_SLVS; i = i + 1) begin
            if (r_slv_hsel[i]) begin
                slv_hready_mux = slv_hready_in_v[i];
                slv_hresp_mux  = slv_hresp_v[i];
                slv_hrdata_mux = slv_hrdata_v[i];
            end
        end
    end

    assign s_dec_hready = (|r_slv_hsel) ? slv_hready_mux : def_slave_hready;

    // -----------------------------------------------------------------------
    // master_sel / r_master_sel pipeline
    // -----------------------------------------------------------------------
    assign htrans_of_sel = mst_htrans[2*master_sel[2:0]+:2]; // htrans of current bus owner

    always @(*) begin
        s_master_sel   = (s_dec_hready) ? s_grant_master : master_sel;
        s_r_master_sel = (s_dec_hready && htrans_reg != `BUSY) ? master_sel : r_master_sel;
    end

    always @(posedge hclk or negedge hresetn) begin
        if (!hresetn) begin
            grant_master  <= DEF_ARB_MST[3:0];
            master_sel    <= DEF_ARB_MST[3:0];
            r_master_sel  <= DEF_ARB_MST[3:0];
            turn          <= 4'd0;
            htrans_reg    <= `IDLE;
        end else begin
            grant_master  <= s_grant_master;
            master_sel    <= s_master_sel;
            r_master_sel  <= s_r_master_sel;
            turn          <= s_turn;
            htrans_reg    <= (master_sel != NUM_ARB_MSTS[3:0]) ? sel_htrans : `IDLE;
        end
    end

    // -----------------------------------------------------------------------
    // Arbitration update
    // -----------------------------------------------------------------------
    always @(*) begin
        s_grant_master = grant_master;
        s_turn = turn;

        if (slv_hready_mux) begin
            if (((grant_master != NUM_ARB_MSTS[3:0]) &&
                 (mst_htrans[2*grant_master+:2] != `BUSY) &&
                 (htrans_reg != `BUSY)) ||
                (grant_master == NUM_ARB_MSTS[3:0])) begin

                if (req_ored) begin
                    case (ALG_NUMBER)
                        0, 3: begin // fixed (and fair-fixed)
                            if (ALG_NUMBER == 0 || !hbusreq_msk[grant_master]) begin
                                // fixed priority: highest numbered requesting master wins
                                s_grant_master = 4'd0;
                                for (i = 0; i < NUM_ARB_MSTS; i = i + 1)
                                    if (hbusreq_msk[i]) s_grant_master = i[3:0];
                            end
                        end
                        1, 4: begin // round-robin
                            if (ALG_NUMBER == 1 || !hbusreq_msk[grant_master]) begin
                                // Simple round-robin from current turn
                                begin: rr_block
                                    integer k;
                                    for (k = 0; k < NUM_ARB_MSTS; k = k + 1) begin
                                        integer idx;
                                        idx = (turn + k) % NUM_ARB_MSTS;
                                        if (hbusreq_msk[idx]) begin
                                            s_grant_master = idx[3:0];
                                            s_turn = idx[3:0];
                                            disable rr_block;
                                        end
                                    end
                                end
                            end
                        end
                        2, 5: begin // random
                            if (ALG_NUMBER == 2 || !hbusreq_msk[grant_master]) begin
                                // Random priority starting from random index
                                begin: ran_block
                                    integer k2, idx2;
                                    for (k2 = 0; k2 < NUM_ARB_MSTS; k2 = k2 + 1) begin
                                        idx2 = (random + k2) % NUM_ARB_MSTS;
                                        if (hbusreq_msk[idx2]) begin
                                            s_grant_master = idx2[3:0];
                                            s_turn = (turn == NUM_ARB_MSTS-1) ? 4'd0 : turn + 4'd1;
                                            disable ran_block;
                                        end
                                    end
                                end
                            end
                        end
                        default: s_grant_master = grant_master;
                    endcase
                end else if (!split_reg[DEF_ARB_MST]) begin
                    s_grant_master = DEF_ARB_MST[3:0];
                    s_turn         = DEF_ARB_MST[3:0];
                end else begin
                    s_grant_master = NUM_ARB_MSTS[3:0]; // dummy master
                end
            end
        end
    end

    // -----------------------------------------------------------------------
    // LFSR for random arbitration
    // -----------------------------------------------------------------------
    always @(*) begin
        s_seed[9:1] = seed[8:0];
        s_seed[0]   = ~(seed[9] ^ seed[6]);
    end

    always @(posedge hclk or negedge hresetn) begin
        if (!hresetn) begin
            seed   <= 10'b0;
            random <= 4'd0;
        end else begin
            seed <= s_seed;
            if (seed[3:0] < NUM_ARB_MSTS[3:0])
                random <= seed[3:0];
            else
                random <= turn;
        end
    end

    // -----------------------------------------------------------------------
    // Master MUX – select bus signals from winning master
    // -----------------------------------------------------------------------
    always @(*) begin
        // Defaults (default master)
        sel_haddr  = mst_haddr[DEF_ARB_MST];
        sel_hwrite = mst_hwrite[DEF_ARB_MST];
        sel_hsize  = mst_hsize[DEF_ARB_MST];
        sel_hburst = mst_hburst[DEF_ARB_MST];
        sel_hprot  = mst_hprot[DEF_ARB_MST];
        sel_htrans = mst_htrans[2*DEF_ARB_MST+:2];
        sel_hwdata = mst_hwdata[DEF_ARB_MST];
        for (i = 0; i < NUM_ARB_MSTS; i = i + 1) begin
            if (r_master_sel == i[3:0])
                sel_hwdata = mst_hwdata[i];
            if (master_sel == i[3:0]) begin
                sel_haddr  = mst_haddr[i];
                sel_hwrite = mst_hwrite[i];
                sel_hsize  = mst_hsize[i];
                sel_hburst = mst_hburst[i];
                sel_hprot  = mst_hprot[i];
                sel_htrans = mst_htrans[2*i+:2];
            end
        end
        if (master_sel == NUM_ARB_MSTS[3:0])
            sel_htrans = `IDLE;
    end

    // grant output
    generate
        genvar g;
        for (g = 0; g < 15; g = g + 1) begin : gen_grant
            assign mst_hgrant[g] = (s_grant_master == g[3:0]);
        end
    endgenerate

    assign mst_hready_out = slv_hready_mux;
    assign mst_hresp_out  = slv_hresp_mux;
    assign mst_hrdata_out = slv_hrdata_mux;

    // -----------------------------------------------------------------------
    // AHB Decoder
    // -----------------------------------------------------------------------
    reg  [NUM_SLVS-1:0] hsel_comb;
    reg                  def_slave_hsel_comb;
    reg                  hmastlock_comb;

    function [31:0] get_addr_low;
        input [3:0] idx;
        get_addr_low = ADDR_LOW_FLAT[32*idx+:32];
    endfunction

    function [31:0] get_addr_high;
        input [3:0] idx;
        get_addr_high = ADDR_HIGH_FLAT[32*idx+:32];
    endfunction

    always @(*) begin
        hmastlock_comb = 1'b0;
        for (i = 0; i < NUM_ARB_MSTS; i = i + 1) begin
            if (!hmastlock_comb && master_sel == i[3:0] && mst_hlock[i])
                hmastlock_comb = 1'b1;
        end

        def_slave_hsel_comb = 1'b1;
        for (i = 0; i < NUM_SLVS; i = i + 1) begin
            if (sel_haddr[31:10] >= get_addr_low(i[3:0])[31:10] &&
                sel_haddr[31:10] <= get_addr_high(i[3:0])[31:10]) begin
                hsel_comb[i]        = 1'b1;
                def_slave_hsel_comb = 1'b0;
            end else begin
                hsel_comb[i] = 1'b0;
            end
        end
    end

    assign def_slave_hsel_w = def_slave_hsel_comb;

    // Register slave selects (pipelined)
    always @(posedge hclk or negedge hresetn) begin
        if (!hresetn) begin
            r_slv_hsel       <= {NUM_SLVS{1'b0}};
            r_def_slave_hsel <= 1'b0;
        end else if (s_dec_hready) begin
            r_slv_hsel       <= hsel_comb;
            r_def_slave_hsel <= def_slave_hsel_comb;
        end
    end

    // Slave output assignments
    assign slv_hsel         = hsel_comb;
    assign slv_haddr_out    = sel_haddr;
    assign slv_hwrite_out   = sel_hwrite;
    assign slv_htrans_out   = sel_htrans;
    assign slv_hsize_out    = sel_hsize;
    assign slv_hburst_out   = sel_hburst;
    assign slv_hprot_out    = sel_hprot;
    assign slv_hwdata_out   = sel_hwdata;
    assign slv_hmaster_out  = master_sel;
    assign slv_hmastlock_out= hmastlock_comb;
    assign slv_hready_in    = s_dec_hready;

    // -----------------------------------------------------------------------
    // Default slave
    // -----------------------------------------------------------------------
    always @(posedge hclk or negedge hresetn) begin
        if (!hresetn)
            def_slave_hready <= 1'b1;
        else begin
            if (def_slave_hsel_comb && s_dec_hready && sel_htrans != `IDLE)
                def_slave_hready <= 1'b0;
            else
                def_slave_hready <= 1'b1;
        end
    end

    // -----------------------------------------------------------------------
    // Split register
    // -----------------------------------------------------------------------
    always @(posedge hclk or negedge hresetn) begin
        if (!hresetn) begin
            split_reg <= 15'b0;
        end else begin
            for (j = 0; j < NUM_SLVS; j = j + 1) begin
                for (i = 0; i < NUM_ARB_MSTS; i = i + 1) begin
                    if (slv_hsplit_v[j][i])
                        split_reg[i] <= 1'b0;
                end
                if (r_slv_hsel[j]) begin
                    if (slv_hready_in_v[j] && slv_hresp_v[j] == `SPLIT_RESP &&
                        master_sel != NUM_ARB_MSTS[3:0])
                        split_reg[master_sel] <= 1'b1;
                end
            end
        end
    end

endmodule
